version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/go"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"

    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
      commit-message:
          prefix: "build"
          include: "scope"
