name: generate-go-source

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Generate sources
        run: make clean all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Golang source