name: Test generating sources

on:
  release:
    types: [published]
    tags-ignore:
      - go/v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.head_ref }}
#
#      - name: Setup Go
#        uses: actions/setup-go@v4
#
#      - name: Generate sources
#        run: |
#          PATH=/home/runner/go/bin:${PATH}
#          make clean all
#
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Generate Golang source
