name: Generate Go stubs

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'go/v') == false
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ toJSON(github.event.release.tag_name) }}
          echo ${{ toJSON(github.ref) }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Generate sources
        run: |
          PATH=/home/runner/go/bin:${PATH}
          make clean all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate Golang source

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        env:
          TAG_NAME: ${{ 'go/' + github.event.release.tag_name }}
        with:
          tag: ${{ 'go/' + github.event.release.tag_name }}
          tag_exists_error: false
          message: "Latest release"
